# SELECT CAR_ID, 
#        max(case when '2022-10-16' between start_date and end_date then '대여중' else '대여 가능' end) as AVAILABILITY
# FROM  CAR_RENTAL_COMPANY_RENTAL_HISTORY 
# group by car_id
# ORDER BY car_id desc

SELECT CAR_ID, IF (CAR_ID IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE '2022-10-16' BETWEEN START_DATE AND END_DATE), '대여중', '대여 가능')AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
ORDER BY CAR_ID DESC